# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose

version: '3.3'

services:
  frontend:
    image: peke.plab.fi:5050/frostbit-web/tunne-app-frontend:latest
    ports:
      - 8220:4173
#    env_file:
#      - backend.env