version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: "1.0.0" # Leave empty to not display version
        API_URL: "http://localhost:8001" # Backend API URL
    ports:
      - "4173:4173"
    environment:
      - VITE_APP_VERSION=${APP_VERSION}
      - VITE_API_URL=${API_URL}
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "preview"]
